### ISSUE TITLE
你好，怎么可以把她嵌入到我的博客园页面上

### ISSUE THREAD

**Issue by sweetalin** [shalldie/chuncai#4]
看到有一个人他的页面上有这样一个动画，很可爱i，搜到了这个，可以说明一下吗

**Comment by shalldie** [comment]
@sweetalin 
https://github.com/shalldie/chuncai/blob/master/index.html
如上demo，引入 jq 跟 chuncai.js 之后，调用一下就行。
因为这个是私人项目，建议你重新构建一下，因为默认的导航中含有我的链接。

**Comment by sweetalin** [comment]
我在博客园的设置页面只看到了页首 、侧边栏和页尾 css设置和js 设置，像一些时间钟，小仓鼠什么的复制上去就可以用，这个是还需要自己去写一些前端代码？我是后端开发的，前端只是懂一点点，可以详细说一下吗？谢谢
另：我在一篇博客上看到有人做的 wordpress 的一个小程序，做的是伪春菜 ，那个还需要数据库导入数据什么的，做的效果也不错，这个你怎么看。

**Comment by shalldie** [comment]
额，你说的那些应该是引用后就自动调用的。
这个春菜之所以需要手动调用，是因为可以自定义一些参数的，在初始化的时候可以传入一些自定义、扩展的内容。

从数据库导入？ 可能是页面静态化的时候生成，或者数据需要动态从接口加载吧，，这个没啥看法，前端很繁荣

**Comment by sweetalin** [comment]
哈哈，好的。说起来我昨天看的那篇博客是你的吗？就是页面上有心跳图片轮播的那个

**Comment by shalldie** [comment]
cnblogs.com/lianmin

**Comment by sweetalin** [comment]
有必要扒一扒你是男是女~~

**Comment by shalldie** [comment]
=。=  本人痴汉

**Comment by sweetalin** [comment]
我很喜欢【邪恶的笑( ‵▽′)ψ】
